spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: authorization
          uri: https://authorization-8wr6.onrender.com
          predicates:
            - Path=/authorization/**
          filters:
            - RewritePath=/authorization/(?<remaining>.*), /${remaining}
        - id: category
          uri: https://category-3b4h.onrender.com
          predicates:
            - Path=/category/**
          filters:
            - RewritePath=/category/(?<remaining>.*), /${remaining}

