spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - http://192.168.188.29:4200
              - http://localhost:4200
              - https://localhost
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Content-Type
              - X-Requested-With
              - accept
              - Origin
              - Access-Control-Request-Method
              - Access-Control-Request-Headers
              - Access-Control-Allow-Origin
      routes:
        - id: authorization
          uri: https://authorization-8wr6.onrender.com
          predicates:
            - Path=/authorization/**
          filters:
            - RewritePath=/authorization/(?<remaining>.*), /${remaining}
        - id: category
          uri: https://category-3b4h.onrender.com
          predicates:
            - Path=/category/**
          filters:
            - RewritePath=/category/(?<remaining>.*), /${remaining}
        - id: story
          uri: https://story-xci7.onrender.com
          predicates:
            - Path=/story/**
          filters:
            - RewritePath=/story/(?<remaining>.*), /${remaining}

